{% extends 'layout.swig' %}

{% block body %}
Welcome to Charon!

<h2>Important notice</h2>
<p>
<b>Emails are currently not functioning properly.</b>
If you use a provider with tight email requirements, such as Gmail, emails from the auth server or other zandronum.com services may not arrive.
If you encounter such an issue, ask for help in <a href="https://wiki.zandronum.com/Discord">the Zandronum Discord</a>.
</p>
{% endblock %}
